---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: molecule-rocky9-cvmfs
    image: rockylinux:9.3
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
scenario:
  name: default
