---
- name: Converge
  hosts: all

  tasks:
    - name: "Include poolaccounts role"
      include_role:
        name: "poolaccounts"
      vars:
        poolaccounts_enable_gridmapdir: true
        poolaccounts_enable_grid_mapfile: true
        poolaccounts_enable_groupmapfile: true
        poolaccounts_enable_cleanup: true
        poolaccounts:
          - name: 'cms%03d'
            uid: 10000
            number: 5
            step: 2
            description: 'Standard User of the CMS VO'
            group: cms
            gid: 10000
            fqan: /cms
          - name: 'cmsprd%02d'
            uid: 11000
            number: 2
            step: 2
            description: 'Production User of the CMS VO'
            group: cmsprd
            gid: 11000
            groups: cms
            fqan: /cms/Role=production
          - name: 'cmspil%02d'
            uid: 12000
            number: 2
            step: 2
            description: 'Pilot User of the CMS VO'
            group: cmspil
            gid: 12000
            groups: cms
            fqan: /cms/Role=pilot
          - name: cmssgm
            uid: 13000
            description: 'SW User of the CMS VO'
            group: cmssgm
            gid: 13000
            groups: cms
            fqan: /cms/Role=lcgadmin
