---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-role-gridftp
  matrix:
    - MOLECULE_DISTRO: centos:7

install:
  - pip install "molecule==2.22"
  - pip install "ansible==2.9.10"
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  # slack:
  #   rooms:
  #     - '<account>:<token>#devops'
  #   on_success: change # default: always
  #   on_failure: always # default: always
