---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Enable EPEL repository
      package:
        name: epel-release
        state: present
  tasks:
    - name: "Include grid role"
      include_role:
        name: "grid"
      vars:
        grid_vos:
          - cms
          - alice
          - belle
        grid_dummy_host_certificate: true
