---
- name: Converge
  hosts: all

  tasks:
    - name: "Include grid role"
      ansible.builtin.include_role:
        name: clip.grid.grid
      vars:
        grid_vos:
          - cms
          - alice
          - ops
