---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-ubi9.4-1-${INSTANCE_ID:-local}
    image: docker.artifactory.imp.ac.at/vbc/ubi9/tde:9.4-1
provisioner:
  name: ansible
scenario:
  name: default
