---
- name: Prepare
  hosts: all
  tasks:
    - name: Import EPEL Key
      ansible.builtin.rpm_key:
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
        state: present

    - name: Enable EPEL repository
      ansible.builtin.package:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present

    - name: Enable CRB Repository
      ansible.builtin.command: /usr/bin/dnf config-manager --set-enabled crb
      register: enable_crb_result
      changed_when: true
