---
# tasks file for hephy.cvmfs-client
- name: Install and Configure CVMFS repository
  ansible.builtin.import_tasks: repo.yml
  tags: [cvmfs, repos]
  when: cvmfs_manage_yumrepo

- name: Install CVMFS client and configuration packages
  ansible.builtin.import_tasks: packages.yml
  tags: [cvmfs, packages]

- name: Configure CVMFS cache
  ansible.builtin.import_tasks: cache.yml
  tags: [cvmfs, cache]

- name: Configure CVMFS
  ansible.builtin.import_tasks: config.yml
  tags: [cvmfs, config]

- name: Mount CVMFS repositories
  ansible.builtin.import_tasks: mount.yml
  tags: [cvmfs, mount]

- name: Test CVMFS
  ansible.builtin.import_tasks: test.yml
  tags: [cvmfs, test]
