---
- name: packages | Install CVMFS client and configuration packages
  ansible.builtin.package:
    name: "{{ ['cvmfs'] + cvmfs_config_repos }}"

- name: packages | Install AutoFS package
  ansible.builtin.package:
    name: autofs
    state: present
  when: cvmfs_auto_setup | bool
