---
- name: repo | Install CVMFS repository
  vars:
    cvmfs_repo_pkg: "{{ cvmfs_manage_yumrepo | ternary('https://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs-release-latest.noarch.rpm', 'cvmfs-release-*') }}"
  ansible.builtin.dnf:
    name: "{{ cvmfs_repo_pkg }}"
    state: "{{ cvmfs_manage_yumrepo | ternary('installed', 'absent') }}"
    disable_gpg_check: true
