---
- name: repo | Install CernVM GPG key
  ansible.builtin.rpm_key:
    key: https://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM
    state: present
    validate_certs: true
    fingerprint: "70B9 8904 8820 8E31 5ED4  5208 230D 389D 8AE4 5CE7"

- name: repo | Install CVMFS repository
  ansible.builtin.dnf:
    name: https://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs-release-latest.noarch.rpm
    state: installed
    disable_gpg_check: true
