---
# tasks file for poolaccounts role
- name: Create gridmapdir
  file:
    path: /etc/grid-security/gridmapdir
    state: directory
    mode: "0755"
  when: poolaccounts_enable_grid_mapfile or poolaccounts_enable_groupmapfile

- name: Create groups for the poolaccounts
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
  loop: "{{ poolaccounts }}"
  when: "poolaccounts_create_accounts | bool"
  loop_control:
    label: "{{ item.group }}"

- name: Create poolaccounts
  include_tasks: poolaccount.yml
  loop: "{{ poolaccounts }}"
  loop_control:
    loop_var: account

- name: Install grid accounts cleanup
  include_tasks: cleanup-grid-accounts.yml
  when: poolaccounts_enable_cleanup

- name: Configure grid-mapfile
  template:
    src: voms-mapfile.j2
    dest: /etc/grid-security/voms-mapfile
    mode: "0644"
  when: poolaccounts_enable_grid_mapfile

- name: Configure groupmapfile
  template:
    src: groupmapfile.j2
    dest: /etc/grid-security/groupmapfile
    mode: "0644"
  when: poolaccounts_enable_groupmapfile
