---
- name: repos | Add Upstream EOS Depends repository
  ansible.builtin.yum_repository:
    name: eos-diopside-depend
    description: EOS 5.x Diopside Depend repo
    state: "{{ (eosxd_use_upstream_repos) | ternary('present', 'absent') }}"
    baseurl: https://storage-ci.web.cern.ch/storage-ci/eos/diopside-depend/el-9/x86_64/
    gpgcheck: false

- name: repos | Add upstream EOS Tag repository
  ansible.builtin.yum_repository:
    name: eos-citrine-tag
    description: EOS 5.x Diopside Tag repo
    state: "{{ (eosxd_use_upstream_repos) | ternary('present', 'absent') }}"
    baseurl: https://storage-ci.web.cern.ch/storage-ci/eos/diopside/tag/testing/el-9/x86_64/
    gpgcheck: false
