---
galaxy_info:
  role_name: gridftp
  namespace: clip
  author: Uemit Seren <uemit.seren@gmi.oeaw.ac.at>
  description: Installation of Globus GRIDFTP
  company: Institute for High Energy Physics, Austrian Academy of Sciences
  issue_tracker_url: https://github.com/clip-hpc/ansible-role-gridftp/issues
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags: []
dependencies: []
