---
# tasks to setup lcmaps authorization

- name: Install lcmaps packages
  yum:
    name:
      - "lcmaps"
      - "lcmaps-plugins-voms"
      - "lcmaps-plugins-basic"
      - "lcmaps-plugins-verify-proxy"
      - "lcas-lcmaps-gt4-interface"
    state: present

- name: Make sure that lcmaps mapfile exist
  file:
    state: touch
    path: "/etc/grid-security/{{ item }}"
    modification_time: preserve
    access_time: preserve
    mode: "0644"
  loop:
    - ban-voms-mapfile
    - ban-mapfile
    - grid-mapfile

- name: Make sure that gridmapdir exists
  file:
    recurse: true
    state: directory
    path: /etc/grid-security/gridmapdir
    mode: "0755"

- name: Copy lcmaps.db file
  copy:
    src: lcmaps.db
    dest: /etc/lcmaps/lcmaps.db
    mode: "0644"

- name: Configure gsi-authz
  copy:
    src: gsi-authz-lcmaps.conf
    dest: /etc/grid-security/gsi-authz.conf
    mode: "0644"
  notify: Restart gridftp-server
