---
ansible:
  executor:
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_PROJECT_DIRECTORY}/extensions/molecule/inventory/
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"


dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/tests/requirements.yml

shared_state: true
