---
galaxy_info:
  role_name: poolaccounts
  namespace: clip
  author: Dietrich Liko
  description: Create pool accounts for grid site
  company: Institute for High energy Physics, Austrian Academy of Sciences
  issue_tracker_url: https://gitlab.cern.ch/hephyvienna/ansible/role/poolaccounts/issues
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags: []
