---
- name: Install argus packages
  package:
    name:
      - argus-pep-api-c
      - argus-gsi-pep-callout
    state: present

- name: Configure gsi-authz
  template:
    src: gsi-authz-argus.conf.j2
    dest: /etc/grid-security/gsi-authz.conf
    mode: "0644"
  notify: reconfigure htcondor_ce

- name: Configure gsi-pep-callout-condor
  template:
    src: gsi-pep-callout-condor.conf.j2
    dest: /etc/grid-security/gsi-pep-callout-condor.conf
    mode: "0644"
  notify: reconfigure htcondor_ce
