- name: Configure lcmaps authorization
  yum:
    name:
      - "lcmaps"
      - "lcmaps-plugins-voms"
      - "lcmaps-plugins-basic"
      - "lcmaps-plugins-verify-proxy"
      - "lcas-lcmaps-gt4-interface"
    state: present

    #- name: Copy lcmaps plugion so files
    # copy:
    # remote_src: true
    #src: "/usr/lib64/lcmaps/{{ item }}.so"
    # dest: "/usr/lib64/lcmaps/{{ item }}2.so"
    # mode: 755
    # loop:
    # - liblcmaps_voms_localaccount
    # - liblcmaps_verify_proxy

    #- name: Symlink lcmaps plugion mod files
    # file:
    # state: link
    # src: "/usr/lib64/lcmaps/{{ item.src }}"
    # dest: "/usr/lib64/lcmaps/{{ item.dest }}"
    # loop:
    # - { src: liblcmaps_voms_localaccount2.so, dest: lcmaps_voms_localaccount2.mod }
    # - { src: liblcmaps_verify_proxy2.so, dest: lcmaps_verify_proxy2.mod }

- name: Make sure that lcmaps mapfile exist
  file:
    state: touch
    path: "/etc/grid-security/{{ item }}"
    modification_time: preserve
    access_time: preserve
    mode: "0644"
  loop:
    - ban-voms-mapfile
    - ban-mapfile

- name: Make sure that gridmapdir is owned by condor
  file:
    recurse: true
    state: directory
    owner: condor
    mode: "0755"
    path: /etc/grid-security/gridmapdir

- name: Copy lcmaps.db file
  copy:
    src: lcmaps.db
    dest: /etc/lcmaps.db
    mode: "0644"

- name: Configure gsi-authz
  template:
    src: gsi-authz-lcmaps.conf.j2
    dest: /etc/grid-security/gsi-authz.conf
    mode: "0644"
  notify: reconfigure htcondor_ce
