---
- name: htcondor-ce | Install pkgs
  ansible.builtin.package:
    name:
      - 'htcondor-ce-client'
      - "htcondor-ce-view"
      - "htcondor-ce"
      - "htcondor-ce-{{ htcondor_ce_lrms }}"
    state: installed

- name: htcondor-ce | Configure HTCondor CE
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/condor-ce/{{ item.dest }}"
    mode: "0644"
  loop:
    - src: local.conf.j2
      dest: config.d/99-local.conf
    - src: files/01-ce-auth.conf
      dest: config.d/01-ce-auth.conf
    - src: files/90-ssl-auth.conf
      dest: config.d/90-ssl-auth.conf
    - src: files/99-voms.conf
      dest: config.d/99-voms.conf
    - src: files/99-debug.conf
      dest: config.d/99-debug.conf
  notify: Reconfigure htcondor_ce

- name: htcondor-ce | Copy HTCondor-CE mapfiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/condor-ce/mapfiles.d/"
    mode: "0644"
  loop: "{{ htcondor_ce_mapfiles }}"
  notify: Reconfigure htcondor_ce

- name: htcondor-ce | Configure HTCondor CE job routes
  ansible.builtin.template:
    src: "{{ htcondor_ce_job_route_file }}"
    dest: /etc/condor-ce/config.d/
    mode: "0644"
  when: htcondor_ce_job_route_file and htcondor_ce_job_route_file | default('') | length > 0
  notify: Reconfigure htcondor_ce

- name: htcondor-ce | Disable WN proxy renewal
  ansible.builtin.lineinfile:
    state: present
    line: "{{ item.line }}"
    regex: "{{ item.regex }}"
    path: /etc/blah.config
  loop:
    - line: blah_disable_wn_proxy_renewal=yes
      regex: '^blah_disable_wn_proxy_renewal'
    - line: blah_delegate_renewed_proxies=no
      regex: '^blah_delegate_renewed_proxies'
    - line: blah_disable_limited_proxy=yes
      regex: '^blah_disable_limited_proxy'
    - line: "blah_shared_directories={{ htcondor_ce_shared_dir | unique | join(':') }}"
      regex: '^blah_shared_directories'


- name: htcondor-ce | Create condor spool directory
  ansible.builtin.file:
    state: directory
    group: condor
    owner: condor
    mode: "0755"
    path: "{{ htcondor_ce_spool_dir }}"
  when: htcondor_ce_spool_dir is defined and htcondor_ce_spool_dir

- name: htcondor-ce | Start HTCondor CE
  ansible.builtin.service:
    name: condor-ce
    state: started
    enabled: true
