---
# tasks file for htcondor-ce role
- name: Install repositories
  ansible.builtin.import_tasks: repos.yml
  tags: ['htcondor-ce', 'repos']

- name: Install HTCondor CE
  ansible.builtin.import_tasks: htcondor-ce.yml
  tags: ['htcondor-ce', 'install']

- name: Install APEL
  ansible.builtin.include_tasks: apel.yml
  tags: ['htcondor-ce', 'apel']
  when: ansible_facts['distribution_major_version'] != '10' # FIXME: skip because of missing dependencies for RHEL10
