---
# tasks file for htcondor-ce role
- name: Install repositories
  ansible.builtin.import_tasks: repos.yml
  when: htcondor_ce_repo_install
  tags: ['htcondor-ce', 'repos']

- name: Install HTCondor CE
  ansible.builtin.import_tasks: htcondor-ce.yml
  tags: ['htcondor-ce', 'install']

- name: Install APEL
  ansible.builtin.import_tasks: apel.yml
  tags: ['htcondor-ce', 'apel']
