---
- name: repos | Imort HTCondor GPG key
  ansible.builtin.rpm_key:
    key: "https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-23.x-Key"
    state: present

- name: repos | Install HTCondor stable repository
  ansible.builtin.package:
    name: "https://research.cs.wisc.edu/htcondor/repo/23.x/htcondor-release-current.el9.noarch.rpm"
    state: installed
