---
- name: Install HTCondor stable repository
  package:
    name: "https://research.cs.wisc.edu/htcondor/repo/9.0/htcondor-release-current.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: installed
