---
# defaults file for poolaccounts role

poolaccounts_homedir: /home
poolaccounts: []
poolaccounts_enable_gridmapdir: false
poolaccounts_enable_grid_mapfile: false
poolaccounts_enable_groupmapfile: false
poolaccounts_enable_cleanup: false
poolaccounts_cleanup_uid_min: 1000
poolaccounts_cleanup_verbose: false
poolaccounts_create_accounts: true
