---
# tasks file for clip.grid.vobox


- name: Assert that account is provided
  ansible.builtin.assert:
    that:
      - vobox_account is defined
      - vobox_account.name is defined
      - vobox_account.uid is defined
      - vobox_account.group is defined
      - vobox_account.gid is defined
      - vobox_account.vo is defined
      - vobox_account.fqan is defined


- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: installed

- name: Make sure that firewalld is running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Install WLCG VOBOX
  ansible.builtin.package:
    name: wlcg-vobox
    state: installed

- name: Template site config, users and groups
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/root/{{ item }}"
    mode: "0644"
  loop:
    - site-info.def
    - groups.conf
    - users.conf
  notify: Configure VOBOX
