---
- name: Converge
  hosts: all
  tasks:
    - name: Include vobox role
      ansible.builtin.include_role:
        name: vobox
      vars:
        vobox_create_user: true
        vobox_host: vobox.grid.vbc.ac.at
        vobox_sitename: T2_AT_VIENNA
        vobox_vo: alice
        vobox_account:
          name: "grid.alice.smg01"
          uid: 45450
          group: role.grid.alice.sgm
          gid: 45450
          vo: alice
          fqan: /alice/Role=lcgadmin
          mappings:
            - /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=grigoras/CN=650724/CN=Costin Grigoras
            - /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=lbetev/CN=374855/CN=Latchezar Betev
            - /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=maarten/CN=410032/CN=Maarten Litmaath
            - /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mstoretv/CN=767601/CN=Maksim Melnik Storetvedt
