---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: molecule-rocky9-vobox
    hostname: vobox.grid.vbc.ac.at
    image: rockylinux-systemd:9.3
    privileged: true # required for DBUS
    command: /usr/sbin/init
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
