---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Import EPEL Key
      ansible.builtin.rpm_key:
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
        state: present

    - name: Enable EPEL repository
      ansible.builtin.package:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present

    - name: Enable CRB Repository
      ansible.builtin.command: /usr/bin/dnf config-manager --set-enabled crb
      register: enable_crb_result
      changed_when: true

    - name: Make sure that cronie is installed
      ansible.builtin.package:
        name: cronie
        state: present

    - name: Make sure that DBUS is running # required for YAIM
      ansible.builtin.service:
        name: dbus
        state: started
        enabled: true

    - name: Configure CA and dummy hostcert
      ansible.builtin.import_tasks: tasks/ca.yml

    - name: "Include grid role"
      ansible.builtin.include_role:
        name: grid
      vars:
        grid_vos:
          - alice
        grid_host_certificate:
          cert: /srv/certificates/host.crt
          key: /srv/certificates/host.key
          remote_src: true
