---
# handlers file for hephyvienna.htcondor-ce
- name: Reconfigure htcondor_ce
  ansible.builtin.command: /usr/bin/condor_ce_reconfig
  changed_when: true

- name: Restart htcondor_ce
  ansible.builtin.service:
    name: condor-ce
    state: restarted
