---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Enable EPEL repository
      package:
        name: epel-release
        state: present
  tasks:
    - name: "Include gridftp role"
      include_role:
        name: "gridftp"
      vars:
        role_gridftp_datainterface: gridftp.grid.vbc.ac.at
