---
- name: Prepare
  hosts: all
  tasks:
    - name: Ensure gnupg2 is installed
      ansible.builtin.package:
        name: gnupg2
        state: present

    - name: Install EPEL release
      ansible.builtin.package:
        name: epel-release
        state: present

    - name: Enable CRB Repository
      ansible.builtin.command: /usr/bin/dnf config-manager --set-enabled crb
      register: enable_crb_result
      changed_when: true
