---
- name: Converge
  hosts: all

  tasks:
    - name: "Include htcondor role"
      ansible.builtin.include_role:
        name: clip.grid.htcondor_ce
      vars:
        htcondor_ce_lrms: slurm
        htcondor_ce_apel_site_name: MySite
