---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: molecule-rocky9-htcondorce
    hostname: ce-9.grid.vbc.ac.at
    image: quay.io/rockylinux/rockylinux:9-ubi-init
    pre_build_image: true
    privileged: true # required for DBUS
    command: /usr/sbin/init
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    tmpfs:
      /run: rw
      /tmp: rw
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
verifier:
  name: ansible
