---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-${INSTANCE_ID:-local}
    image: ${MOLECULE_IMAGE:-'centos/systemd'}
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-'/usr/sbin/init'}
provisioner:
  name: ansible
verifier:
  name: testinfra
