---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-centos7-${INSTANCE_ID:-local}
    hostname: ce-7.grid.vbc.ac.at
    image: centos/systemd:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # - name: instance-stream8-${INSTANCE_ID:-local}
  #   image: quay.io/centos/centos:stream8
  #   hostname: ce-8.grid.vbc.ac.at
  #   command: /sbin/init
  #   pre_build_image: true
  #   capabilities:
  #     - SYS_ADMIN
  #   tmpfs:
  #     - /tmp
  #     - /run
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: testinfra
