---
all:
  hosts:
    container_rockylinux9:
      container_image: quay.io/rockylinux/rockylinux:9-ubi-init
      container_privileged: true
    # container_rockylinux10:
    #   container_image: quay.io/rockylinux/rockylinux:10-ubi-init
    #   container_privileged: true
