---
cvmfs_yumrepo_url: http://cern.ch/cvmrepo/yum/cvmfs/EL/7/x86_64
cvmfs_yumrepo_testing_url: http://cern.ch/cvmrepo/yum/cvmfs-testing/EL/7/x86_64
cvmfs_yumrepo_config_url: http://cern.ch/cvmrepo/yum/cvmfs-config/EL/7/x86_64
cvmfs_fuse_group: false
