---
# defaults file for grid role
grid_install_wlcg_repo: true
grid_install_umd_repo: true
grid_enable_fetch_crl: true
grid_enable_certificates: true
grid_fetchcrl_options: []
grid_vos: []
grid_host_certificate: {}

# Set to ui or wn if the node should also be configured either as a UI or WN node
grid_node_type:

# Installs HEP_OS package. Only relevant when grid_node_type is set to UI or WN
grid_install_hepos: true
