---
- name: Install Copr repository
  yum_repository:
    name: dliko-empty-ca-policy
    description: Copr repo for empty-ca-policy owned by dliko
    baseurl: "https://copr-be.cloud.fedoraproject.org/results/dliko/empty-ca-policy/epel-{{ ansible_distribution_major_version }}-$basearch/"
    skip_if_unavailable: true
    gpgcheck: true
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/dliko/empty-ca-policy/pubkey.gpg
    repo_gpgcheck: false
    enabled: true

- name: Install the dummy ca policies
  package:
    name: dummy-ca-policy
    state: present

- name: Create link to CVMFS directory
  file:
    path: "{{ grid_security_dir }}/certificates"
    src: /cvmfs/grid.cern.ch/etc/grid-security/certificates
    state: link
