---
- name: hostcert | Install host certificate
  ansible.builtin.copy:
    src: "{{ grid_host_certificate.cert }}"
    dest: "{{ grid_security_dir }}/hostcert.pem"
    setype: etc_t
    mode: "0644"


- name: hostcert | Install host private key
  ansible.builtin.copy:
    src: "{{ grid_host_certificate.key }}"
    dest: "{{ grid_security_dir }}/hostkey.pem"
    setype: etc_t
    mode: "0400"
