---
- name: hostcert | Install host certificate
  ansible.builtin.copy:
    src: "{{ grid_host_certificate.cert }}"
    dest: "/etc/grid-security/hostcert.pem"
    setype: etc_t
    mode: "0644"
    remote_src: "{{ grid_host_certificate.remote_src | default(false) }}"


- name: hostcert | Install host private key
  ansible.builtin.copy:
    src: "{{ grid_host_certificate.key }}"
    dest: "/etc/grid-security/hostkey.pem"
    setype: etc_t
    mode: "0400"
    remote_src: "{{ grid_host_certificate.remote_src | default(false) }}"
