---
# tasks file for grid role

- name: Install IGTF Repository and packages
  ansible.builtin.include_tasks: igtf.yml

- name: Configure UMD and WLCG repositories
  ansible.builtin.include_tasks: repos.yml

- name: Install and configure fetch-crl
  ansible.builtin.include_tasks: fetch-crl.yml
  when: grid_enable_fetch_crl | bool

- name: Install VOMS
  ansible.builtin.include_tasks: voms.yml

- name: Install host certificate
  ansible.builtin.include_tasks: hostcert.yml
  when: grid_host_certificate | length > 0
