---
# Configure WLCG and UMD repositories

# - name: Install yum priorities
#   ansible.builtin.package:
#     name: yum-priorities
#     state: present


- name: repos | Configure WLCG repository
  when: grid_install_wlcg_repo | bool
  block:
    - name: repos | Import WLCG gpgpkey
      ansible.builtin.rpm_key:
        state: present
        key: "http://linuxsoft.cern.ch/wlcg/RPM-GPG-KEY-wlcg"

    - name: repos | Install WLCG release repository
      ansible.builtin.package:
        name: "http://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-repo-1.0.0-1.el9.noarch.rpm"
        state: present


- name: repos | Configure UMD repositories
  when: grid_install_umd_repo | bool
  block:
    - name: "repos | Import UMD GPG keys"
      ansible.builtin.rpm_key:
        state: "present"
        key: "{{ item }}"
      loop:
        - "https://repository.egi.eu/sw/production/umd/UMD-5-RPM-PGP-KEY"
        - "https://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY"

    - name: repos | Install UMD release repository
      ansible.builtin.package:
        name: "https://repository.egi.eu/sw/production/umd/5/al9/release/x86_64/umd-release-5.0.0-1.al9.alma.noarch.rpm"
        state: present
