---
- name: Install yum priorities
  package:
    name: yum-priorities
    state: present
  failed_when: false

- block:
  - name: Install UMD base repository
    yum_repository:
      name: "UMD-{{ grid_umd_version }}-base"
      description: "UMD{{ grid_umd_version }} Base repository"
      baseurl: "http://repository.egi.eu/sw/production/umd/{{ grid_umd_version }}/{{ os_name }}/$basearch/base"
      enabled: true
      exclude: "{{ grid_umd_repo_exclude | join(' ') }}"
      includepkgs: "{{ grid_umd_repo_includepkgs | join(' ') }}"
      gpgcheck: true
      gpgkey: >-
        {% for k in grid_umd_repo_rpmgpgkeys -%}
          file:///etc/pki/rpm-gpg/{{ k }}
        {%- endfor %}
      priority: "{{ grid_umd_repo_priority | string }}"
      protect: true

  - name: Install UMD updates repository
    yum_repository:
      name: "UMD-{{ grid_umd_version }}-updates"
      description: "UMD{{ grid_umd_version }} updates repository"
      baseurl: "http://repository.egi.eu/sw/production/umd/{{ grid_umd_version }}/{{ os_name }}/$basearch/updates"
      enabled: true
      exclude: "{{ grid_umd_repo_exclude | join(' ') }}"
      includepkgs: "{{ grid_umd_repo_includepkgs | join(' ') }}"
      gpgcheck: true
      gpgkey: >-
        {% for k in grid_umd_repo_rpmgpgkeys -%}
          file:///etc/pki/rpm-gpg/{{ k }}
        {%- endfor %}
      priority: "{{ grid_umd_repo_priority | string }}"
      protect: true

  - name: Copy gpgkeys
    copy:
      src: "{{ item }}"
      dest: "/etc/pki/rpm-gpg/{{ item }}"
      mode: "0644"
    loop: "{{ grid_umd_repo_rpmgpgkeys }}"

  - name: Import gpgkeys
    rpm_key:
      state: present
      key: "/etc/pki/rpm-gpg/{{ item }}"
    loop: "{{ grid_umd_repo_rpmgpgkeys }}"
  when: grid_enable_umd_repo | bool


- name: Install WLCG repository
  yum_repository:
    name: wlcg
    description: WLCG repoitory
    baseurl: "{{ grid_repo_wlcg_url }}"
    enabled: "{{ grid_repo_wlcg_enabled }}"
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-wlcg
    priority: "{{ grid_repo_wlcg_priority }}"

- name: Copy WLCG gpgkey
  copy:
    src: RPM-GPG-KEY-wlcg
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-wlcg
    mode: "0644"

- name: Import WLCG gpgkey
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-wlcg