---
- name: voms | Install VOMS CA files
  when: not (grid_use_cvmfs_for_voms_certs | bool)
  block:
    - name: voms | Install VOMS files
      vars:
        grid_voms_package: "wlcg{{ (item == 'belle') | ternary('', '-iam') + '-vomses-' + item }}"
      ansible.builtin.package:
        state: installed
        name: "{{ grid_voms_package }}"
      loop: "{{ grid_vos }}"
      when: item in ['alice', 'atlas', 'cms', 'dteam', 'lhcb', 'ops', 'belle']


    - name: voms | Install VOMS LSC files
      vars:
        grid_lsc_package: "wlcg{{ (item == 'belle') | ternary('', '-iam') + '-lsc-' + item }}"
      ansible.builtin.package:
        state: installed
        name: "{{ grid_lsc_package }}"
      loop: "{{ grid_vos }}"
      when: item in ['alice', 'atlas','dteam', 'cms', 'lhcb', 'ops', 'belle']

    - name: voms | Ensure vomsdir exists
      ansible.builtin.file:
        path: /etc/grid-security/vomsdir/belle
        state: directory
        owner: root
        group: root
        mode: '0755'


- name: voms | Configure X509_VOMSES and X509_VOMS_DIR environment variables
  when: grid_use_cvmfs_for_voms_certs | bool
  block:
    - name: voms | Create profile.d file for VOMS environment variables
      ansible.builtin.copy:
        dest: /etc/profile.d/voms.sh
        content: |
          export X509_VOMSES=/cvmfs/grid.cern.ch/etc/grid-security/vomses
          export X509_VOMS_DIR=/cvmfs/grid.cern.ch/etc/grid-security/vomsdir
        owner: root
        group: root
        mode: '0644'
