---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-rocky9-${INSTANCE_ID:-local}
    image: rockylinux:9.3
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
