---
# defaults file for htcondor-ce role
htcondor_ce_repo_install: true
htcondor_ce_spool_dir:
htcondor_ce_home_dir: /users
htcondor_ce_job_routes: []
htcondor_ce_shared_dir: ["{{ htcondor_ce_spool_dir }}", "{{ htcondor_ce_home_dir }}"]
htcondor_ce_lrms: "slurm"
htcondor_ce_apel_db_hostname: localhost
htcondor_ce_apel_db_username: apel
htcondor_ce_apel_db_password:
htcondor_ce_apel_site_name:
htcondor_ce_apel_spec_value: 1.0
htcondor_ce_apel_spec_type: HEPSPEC
htcondor_ce_mapfiles: []
htcondor_ce_job_route_file:
